name: build-server

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: cd server && yarn

      - name: Build server
        run: cd server && yarn build
