name: build-server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/gateway/**"

defaults:
  run:
    working-directory: ./packages/gateway

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: npm ci

      - name: Copy env vars
        run: cp ~/.config/varba7/weather-server .env.local

      - name: Build server
        run: npm run build

      - name: Copy server resources
        run: cp -af . ~/server
