name: build-web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/ui/web/**"
      - "packages/ui/mobile/app/**"

defaults:
  run:
    working-directory: ./packages/ui/web

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"

      - name: Install dependencies
        run: npm ci

      - name: Copy env vars
        run: cp ~/.config/varba7/weather-web .env.local

      - name: Build web
        run: npm run build

      - name: Copy web resource
        run: cp -af ./dist/. /var/www/html/
